#推送完镜像，根据yaml文件生成pod
apiVersion: apps/v1
kind: Deployment
#metadata：包含Pod的一些meta信息，比如名称（部署名称）、namespace(项目空间)、标签等信息。
metadata:
  name: sb001122
  namespace: test  #在test001项目（namespace）下创建容器
  labels:
    app: sb001122
spec: #specification ofn the resource content 指定该资源的内容   
  replicas: 1
  selector:
    matchLabels:
      app: sb001122
  template:
    metadata:
      labels:
        app: sb001122
    spec:
      containers:
        - name: sb001122
          image: '10.84.4.85/test001/springboot-demo:v2'
          ports:
            - name: http-0
              containerPort: 8080
              protocol: TCP
          resources: {}
          # lifecycle:
          #     postStart:
          #       exec:
          #         command:
          #           - echo "helloword!"
          #     preStop:
          #       exec:
          #         command:
          #           - echo "goodBye"
      restartPolicy: Always #表明该容器一直运行，默认k8s的策略，在此容器退出后，会立即创建一个相同的容器   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb001122
  name: sb001122
  namespace: test
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sb001122

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb0033
  name: sb0033
  namespace: test
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sb0033
---
apiVersion: apps/v1
kind: Deployment
#metadata：包含Pod的一些meta信息，比如名称（部署名称）、namespace(项目空间)、标签等信息。
metadata:
  name: sb0033
  namespace: test  #在test001项目（namespace）下创建容器
  labels:
    app: sb0033
spec: #specification of the resource content 指定该资源的内容   
  replicas: 1
  selector:
    matchLabels:
      app: sb0033
  template:
    metadata:
      labels:
        app: sb0033
    spec:
      containers:
        - name: sb0033
          image: '10.84.4.85/test001/springboot-demo:v1'
          ports:
            - name: http-0
              containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always #表明该容器一直运行，默认k8s的策略，在此容器退出后，会立即创建一个相同的容器   
# ---
# name: yyyyy
